spring:
  devtools:
    remote:
      restart:
        enabled: true # ?? ????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roadtointerview?serverTimezone=UTC&characterEncoding=UTF-8
    username : yg
    password : 1234
    initialization-mode : always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
data:
  secret-key: roadtointerview
  refresh-key: interviewtoroad

server:
  port: 8070
